"""empty message

Revision ID: 1d42b9187fa3
Revises: 7cb8a1529413
Create Date: 2023-07-18 22:52:18.688682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d42b9187fa3'
down_revision = '7cb8a1529413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trip_users_trip_id_trips', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_trip_users_trip_id_trips'), 'trips', ['trip_id'], ['id'])

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('trip_users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trip_users_trip_id_trips'), type_='foreignkey')
        batch_op.create_foreign_key('fk_trip_users_trip_id_trips', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
