"""empty message

Revision ID: 2cb618236443
Revises: 9fc85d4bd043
Create Date: 2023-07-17 20:23:58.285409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb618236443'
down_revision = '9fc85d4bd043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trip_users_trip_id_trips', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_trip_users_trip_id_trips'), 'trips', ['trip_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('trip_users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trip_users_trip_id_trips'), type_='foreignkey')
        batch_op.create_foreign_key('fk_trip_users_trip_id_trips', 'trips', ['trip_id'], ['id'])

    # ### end Alembic commands ###
